### ISSUE TITLE
Práctica 2

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-ingestudiantes#1]
[practca2_interfasGrafica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-ingestudiantes/files/14335131/practca2_interfasGrafica.pdf)
Emmanuel Marx Salazar González
Edgar Axel Sandoval Hernández

**Comment by Daisy-GonzalezLita12** [comment]
Hay compañeros se equivocaron en algunas imágenes. Por favor revísenlo

**Comment by josealfredo79** [comment]
@Daisy-GonzalezLita12 Cual es la calificacion..????

**Comment by Daisy-GonzalezLita12** [comment]
17% de 20% @josealfredo79

**Comment by josealfredo79** [comment]
gracias...
